// Generated by GitHub Copilot
import { createReadStream, existsSync, statSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";

const distDir = join(process.cwd(), "dist");
const port = Number(process.env.PORT || "8090");

const mimeTypes = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
  ".ico": "image/x-icon"
};

/**
 * Generated by GitHub Copilot
 * Resolve a request path into a dist-relative asset path safely.
 */
function resolveAssetPath(urlPath) {
  const normalizedPath = normalize(urlPath).replace(/^\.+/, "");
  const safePath = normalizedPath === "/" ? "/index.html" : normalizedPath;
  return join(distDir, safePath);
}

/**
 * Generated by GitHub Copilot
 * Add baseline security headers for static responses.
 */
function applySecurityHeaders(response) {
  response.setHeader("X-Content-Type-Options", "nosniff");
  response.setHeader("X-Frame-Options", "DENY");
  response.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  response.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
}

/**
 * Generated by GitHub Copilot
 * Serve one static file, with index fallback for client-side routes.
 */
function serveFile(request, response) {
  const requestPath = request.url?.split("?")[0] || "/";
  const assetPath = resolveAssetPath(requestPath);

  let finalPath = assetPath;
  if (!existsSync(assetPath) || statSync(assetPath).isDirectory()) {
    finalPath = join(distDir, "index.html");
  }

  const extension = extname(finalPath).toLowerCase();
  const contentType = mimeTypes[extension] || "application/octet-stream";

  response.statusCode = 200;
  response.setHeader("Content-Type", contentType);
  applySecurityHeaders(response);

  createReadStream(finalPath).pipe(response);
}

const server = createServer((request, response) => {
  if (request.url === "/healthz") {
    response.statusCode = 200;
    response.setHeader("Content-Type", "text/plain; charset=utf-8");
    applySecurityHeaders(response);
    response.end("ok");
    return;
  }

  serveFile(request, response);
});

server.listen(port, "0.0.0.0", () => {
  console.log(`llm-judge frontend listening on ${port}`);
});
