// Generated by GitHub Copilot
interface SummaryCardProps {
  title: string;
  value: string;
  tone: "ok" | "alert" | "neutral";
}

/**
 * Generated by GitHub Copilot
 * Render one run summary metric in a visual card with semantic tone.
 */
export function SummaryCard({ title, value, tone }: SummaryCardProps): JSX.Element {
  return (
    <article className={`summary-card summary-card--${tone}`} aria-label={title}>
      <h3>{title}</h3>
      <p>{value}</p>
    </article>
  );
}
