# Generated by GitHub Copilot
"""Integration tests for llm-judge FastAPI endpoints."""

import os
from pathlib import Path
from uuid import uuid4

from fastapi.testclient import TestClient


TEST_DB_PATH = Path(os.getenv("TEMP", ".")) / f"llm-judge-test-{uuid4().hex}.db"
os.environ["LLM_JUDGE_DB_PATH"] = str(TEST_DB_PATH)
os.environ["LLM_JUDGE_STRICT_PROVIDER"] = "false"

from app.main import app  # noqa: E402


client = TestClient(app)


def _sample_payload(provider: str = "local") -> dict[str, object]:
    """Build deterministic run payloads used by endpoint tests."""
    return {
        "run_name": "support-bot-v2-eval",
        "judge_provider": provider,
        "judge_model": "baseline-judge-v1",
        "items": [
            {
                "item_id": "q1",
                "prompt": "How do I reset my password?",
                "candidate_response": (
                    "Open account settings, choose security, and follow the password reset flow."
                ),
                "reference_response": (
                    "Use account settings and select the password reset option under security."
                ),
            },
            {
                "item_id": "q2",
                "prompt": "How can I contact support?",
                "candidate_response": "Use in-app chat or email support@example.com for assistance.",
                "reference_response": "Use in-app chat or the official support email channel.",
            },
        ],
    }


def test_health_endpoint() -> None:
    """Ensure liveness endpoint returns healthy status."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_run_evaluation_success() -> None:
    """Validate end-to-end run evaluation and persistence response."""
    response = client.post("/api/v1/evals/run", json=_sample_payload())
    assert response.status_code == 200

    body = response.json()
    assert body["summary"]["total_items"] == 2
    assert len(body["results"]) == 2
    assert "run_id" in body


def test_provider_fallback_when_key_missing() -> None:
    """Fallback to local provider when external key is not configured."""
    response = client.post("/api/v1/evals/run", json=_sample_payload(provider="openai"))
    assert response.status_code == 200

    body = response.json()
    assert body["requested_provider"] == "openai"
    assert body["provider_used"] == "local"
    assert body["fallback_used"] is True
    assert len(body["notes"]) >= 1


def test_leaderboard_endpoint() -> None:
    """Ensure leaderboard endpoint returns aggregate entries."""
    client.post("/api/v1/evals/run", json=_sample_payload())
    response = client.get("/api/v1/evals/leaderboard?limit=5")
    assert response.status_code == 200
    assert len(response.json()["entries"]) >= 1


def test_invalid_item_identifier_validation() -> None:
    """Reject unsafe item identifiers through schema validation."""
    payload = _sample_payload()
    payload["items"][0]["item_id"] = "bad$id"

    response = client.post("/api/v1/evals/run", json=payload)
    assert response.status_code == 422
