# Generated by GitHub Copilot
"""Integration tests for llm-judge FastAPI endpoints."""

from dataclasses import replace
import os
from pathlib import Path
from uuid import uuid4

from fastapi.testclient import TestClient
from app.middleware import SimpleRateLimitMiddleware


TEST_DB_PATH = Path(os.getenv("TEMP", ".")) / f"llm-judge-test-{uuid4().hex}.db"
os.environ["LLM_JUDGE_DB_PATH"] = str(TEST_DB_PATH)
os.environ["LLM_JUDGE_STRICT_PROVIDER"] = "false"

from app.main import app  # noqa: E402
from app import main as main_module  # noqa: E402


client = TestClient(app)


# Generated by GitHub Copilot
def _assert_error_contract(
    response,
    expected_status: int,
    expected_code: str,
    expected_message: str | None = None,
    expect_details: bool = False,
) -> None:
    """Validate normalized API error envelopes for contract compliance."""
    assert response.status_code == expected_status
    payload = response.json()
    assert isinstance(payload.get("error"), dict)
    assert payload["error"]["code"] == expected_code
    assert isinstance(payload["error"]["message"], str)
    if expected_message is not None:
        assert payload["error"]["message"] == expected_message
    assert isinstance(payload["error"]["request_id"], str)
    assert payload["error"]["request_id"]
    if expect_details:
        assert "details" in payload["error"]


def _sample_payload(provider: str = "local") -> dict[str, object]:
    """Build deterministic run payloads used by endpoint tests."""
    return {
        "run_name": "support-bot-v2-eval",
        "judge_provider": provider,
        "judge_model": "baseline-judge-v1",
        "items": [
            {
                "item_id": "q1",
                "prompt": "How do I reset my password?",
                "candidate_response": (
                    "Open account settings, choose security, and follow the password reset flow."
                ),
                "reference_response": (
                    "Use account settings and select the password reset option under security."
                ),
            },
            {
                "item_id": "q2",
                "prompt": "How can I contact support?",
                "candidate_response": "Use in-app chat or email support@example.com for assistance.",
                "reference_response": "Use in-app chat or the official support email channel.",
            },
        ],
    }


def _get_rate_limiter() -> SimpleRateLimitMiddleware:
    """Resolve the installed rate limiter middleware instance from app stack."""
    current = app.middleware_stack
    while hasattr(current, "app"):
        if isinstance(current, SimpleRateLimitMiddleware):
            return current
        current = current.app
    raise RuntimeError("SimpleRateLimitMiddleware not found")


def test_health_endpoint() -> None:
    """Ensure liveness endpoint returns healthy status."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_probe_alias_endpoints() -> None:
    """Ensure compatibility probe aliases return expected statuses."""
    health_alias = client.get("/healthz")
    assert health_alias.status_code == 200
    assert health_alias.json()["status"] == "ok"

    ready_alias = client.get("/readyz")
    assert ready_alias.status_code == 200
    assert ready_alias.json()["status"] == "ready"


def test_run_evaluation_success() -> None:
    """Validate end-to-end run evaluation and persistence response."""
    response = client.post("/api/v1/evals/run", json=_sample_payload())
    assert response.status_code == 200

    body = response.json()
    assert body["summary"]["total_items"] == 2
    assert len(body["results"]) == 2
    assert "run_id" in body


def test_provider_fallback_when_key_missing() -> None:
    """Fallback to local provider when external key is not configured."""
    response = client.post("/api/v1/evals/run", json=_sample_payload(provider="openai"))
    assert response.status_code == 200

    body = response.json()
    assert body["requested_provider"] == "openai"
    assert body["provider_used"] == "local"
    assert body["fallback_used"] is True
    assert len(body["notes"]) >= 1


def test_leaderboard_endpoint() -> None:
    """Ensure leaderboard endpoint returns aggregate entries."""
    client.post("/api/v1/evals/run", json=_sample_payload())
    response = client.get("/api/v1/evals/leaderboard?limit=5")
    assert response.status_code == 200
    assert len(response.json()["entries"]) >= 1


def test_limit_query_validation() -> None:
    """Reject out-of-range list query limits through validation contract responses."""
    response = client.get("/api/v1/evals/runs?limit=0")
    _assert_error_contract(
        response,
        expected_status=422,
        expected_code="validation_error",
        expected_message="request_validation_failed",
        expect_details=True,
    )
    assert response.headers.get("X-Request-ID")
    assert response.headers.get("X-Content-Type-Options") == "nosniff"
    assert response.headers.get("X-Frame-Options") == "DENY"


def test_phase1_auth_required_contract(monkeypatch) -> None:
    """Require API key on protected endpoints with normalized unauthorized payloads."""
    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, api_key="phase1-secret"))

    unauthorized = client.get("/api/v1/evals/runs")
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    invalid_key = client.get("/api/v1/evals/runs", headers={"X-API-Key": "wrong"})
    _assert_error_contract(
        invalid_key,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.get("/api/v1/evals/runs", headers={"X-API-Key": "phase1-secret"})
    assert authorized.status_code == 200


def test_phase1_error_contract_response() -> None:
    """Return normalized validation payloads with details for schema errors."""
    response = client.get("/api/v1/evals/runs?limit=0")
    _assert_error_contract(
        response,
        expected_status=422,
        expected_code="validation_error",
        expected_message="request_validation_failed",
        expect_details=True,
    )


def test_rate_limit_enforcement_contract() -> None:
    """Reject excess traffic with normalized 429 payloads and tracing headers."""
    limiter = _get_rate_limiter()
    previous_limit = limiter.max_requests_per_minute

    try:
        limiter.max_requests_per_minute = 1
        limiter.request_log.clear()

        first = client.get("/api/v1/evals/runs")
        assert first.status_code == 200

        second = client.get("/api/v1/evals/runs")
        _assert_error_contract(
            second,
            expected_status=429,
            expected_code="rate_limited",
            expected_message="rate_limited",
        )
        assert second.headers.get("X-Request-ID")
        assert second.headers.get("X-Content-Type-Options") == "nosniff"
        assert second.headers.get("X-Frame-Options") == "DENY"
    finally:
        limiter.max_requests_per_minute = previous_limit
        limiter.request_log.clear()
