# Generated by GitHub Copilot
"""Runtime configuration loading for llm-judge backend."""

from dataclasses import dataclass
import os
from typing import List


def _parse_csv(raw_value: str) -> List[str]:
    """Parse comma-separated values into normalized non-empty entries."""
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def _parse_bool(raw_value: str | None, default: bool) -> bool:
    """Parse environment boolean values with a safe default."""
    if raw_value is None:
        return default
    lowered = raw_value.strip().lower()
    if lowered in {"1", "true", "yes", "on"}:
        return True
    if lowered in {"0", "false", "no", "off"}:
        return False
    return default


def _parse_int(raw_value: str | None, default: int, min_value: int) -> int:
    """Parse constrained integer settings from environment values."""
    if raw_value is None:
        return default
    try:
        parsed = int(raw_value)
    except ValueError:
        return default
    return max(min_value, parsed)


@dataclass(frozen=True)
class Settings:
    """Application settings for API security, runtime, and providers."""

    app_env: str
    allowed_hosts: List[str]
    cors_origins: List[str]
    max_payload_bytes: int
    gzip_minimum_size: int
    enable_hsts: bool
    port: int
    db_path: str
    rate_limit_per_minute: int
    strict_provider: bool
    api_key: str
    openai_api_key: str
    anthropic_api_key: str
    gemini_api_key: str


def load_settings() -> Settings:
    """Load validated runtime configuration with production-safe defaults."""
    return Settings(
        app_env=(os.getenv("LLM_JUDGE_ENV", "development").strip().lower() or "development"),
        allowed_hosts=_parse_csv(
            os.getenv("LLM_JUDGE_ALLOWED_HOSTS", "localhost,127.0.0.1,backend,testserver")
        ),
        cors_origins=_parse_csv(
            os.getenv(
                "LLM_JUDGE_CORS_ORIGINS",
                "http://localhost:8090,http://127.0.0.1:8090",
            )
        ),
        max_payload_bytes=_parse_int(
            os.getenv("LLM_JUDGE_MAX_PAYLOAD_BYTES"),
            default=8_388_608,
            min_value=1_048_576,
        ),
        gzip_minimum_size=_parse_int(
            os.getenv("LLM_JUDGE_GZIP_MINIMUM_SIZE"),
            default=1024,
            min_value=256,
        ),
        enable_hsts=_parse_bool(os.getenv("LLM_JUDGE_ENABLE_HSTS"), default=False),
        port=_parse_int(os.getenv("LLM_JUDGE_PORT"), default=8010, min_value=1),
        db_path=(os.getenv("LLM_JUDGE_DB_PATH", "/app/data/llm_judge.db").strip() or "/app/data/llm_judge.db"),
        rate_limit_per_minute=_parse_int(
            os.getenv("LLM_JUDGE_RATE_LIMIT_PER_MINUTE"),
            default=120,
            min_value=10,
        ),
        strict_provider=_parse_bool(os.getenv("LLM_JUDGE_STRICT_PROVIDER"), default=False),
        api_key=os.getenv("LLM_JUDGE_API_KEY", "").strip(),
        openai_api_key=os.getenv("OPENAI_API_KEY", "").strip(),
        anthropic_api_key=os.getenv("ANTHROPIC_API_KEY", "").strip(),
        gemini_api_key=os.getenv("GEMINI_API_KEY", "").strip(),
    )
