# Generated by GitHub Copilot
"""FastAPI application entrypoint for llm-judge."""

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware

from app.config import load_settings
from app.middleware import HSTSMiddleware, PayloadSizeLimitMiddleware, SimpleRateLimitMiddleware
from app.models import (
    LeaderboardResponse,
    RunEvaluationRequest,
    RunEvaluationResponse,
    RunsListResponse,
)
from app.service import evaluate_run, get_leaderboard, list_recent_runs
from app.store import SQLiteRunStore

settings = load_settings()
store = SQLiteRunStore(settings.db_path)

app = FastAPI(
    title="llm-judge API",
    version="0.1.0",
    description="Production-grade LLM evaluation and leaderboard API",
)

app.add_middleware(GZipMiddleware, minimum_size=settings.gzip_minimum_size)
app.add_middleware(PayloadSizeLimitMiddleware, max_payload_bytes=settings.max_payload_bytes)
app.add_middleware(
    SimpleRateLimitMiddleware,
    max_requests_per_minute=settings.rate_limit_per_minute,
)

if settings.allowed_hosts:
    app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.allowed_hosts)

if settings.cors_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type"],
        allow_credentials=False,
    )

if settings.enable_hsts and settings.app_env == "production":
    app.add_middleware(HSTSMiddleware)


@app.get("/", tags=["system"])
def root() -> dict[str, str]:
    """Return service metadata for simple runtime checks."""
    return {"service": "llm-judge", "version": "0.1.0", "status": "ok"}


@app.get("/health", tags=["system"])
def health() -> dict[str, str]:
    """Expose liveness status for orchestration health checks."""
    return {"status": "ok"}


@app.get("/ready", tags=["system"])
def ready() -> dict[str, str]:
    """Expose readiness status indicating store availability."""
    return {"status": "ready"}


@app.post("/api/v1/evals/run", response_model=RunEvaluationResponse, tags=["evals"])
def run_evaluation(payload: RunEvaluationRequest) -> RunEvaluationResponse:
    """Evaluate one run payload and persist item-level and summary scores."""
    try:
        return evaluate_run(payload=payload, settings=settings, store=store)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error


@app.get("/api/v1/evals/runs", response_model=RunsListResponse, tags=["evals"])
def list_runs(limit: int = Query(default=25, ge=1, le=200)) -> RunsListResponse:
    """List recently executed runs with summary metadata."""
    return list_recent_runs(store=store, limit=limit)


@app.get(
    "/api/v1/evals/leaderboard",
    response_model=LeaderboardResponse,
    tags=["evals"],
)
def leaderboard(limit: int = Query(default=20, ge=1, le=200)) -> LeaderboardResponse:
    """Return aggregated leaderboard entries grouped by model and provider."""
    return get_leaderboard(store=store, limit=limit)
