# Generated by GitHub Copilot
"""Custom middleware for security headers, payload limits, and basic rate limiting."""

from collections import defaultdict, deque
from time import monotonic
from typing import Deque, Dict

from fastapi import HTTPException, status
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response


class PayloadSizeLimitMiddleware(BaseHTTPMiddleware):
    """Reject requests that exceed configured payload size boundaries."""

    def __init__(self, app, max_payload_bytes: int):
        super().__init__(app)
        self.max_payload_bytes = max_payload_bytes

    async def dispatch(self, request: Request, call_next):
        """Check content length before processing application handlers."""
        content_length = request.headers.get("content-length")
        if content_length is not None:
            try:
                parsed = int(content_length)
                if parsed > self.max_payload_bytes:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail="request payload too large",
                    )
            except ValueError:
                raise HTTPException(status_code=400, detail="invalid content-length header")

        return await call_next(request)


class HSTSMiddleware(BaseHTTPMiddleware):
    """Attach strict transport security header for HTTPS deployments."""

    async def dispatch(self, request: Request, call_next):
        """Append HSTS header after handler execution."""
        response: Response = await call_next(request)
        response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
        return response


class SimpleRateLimitMiddleware(BaseHTTPMiddleware):
    """Apply an in-memory fixed-window limit per client IP."""

    def __init__(self, app, max_requests_per_minute: int):
        super().__init__(app)
        self.max_requests_per_minute = max_requests_per_minute
        self.window_seconds = 60.0
        self.request_log: Dict[str, Deque[float]] = defaultdict(deque)

    async def dispatch(self, request: Request, call_next):
        """Track request timestamps and block traffic above configured limits."""
        client_ip = request.client.host if request.client else "unknown"
        now = monotonic()
        bucket = self.request_log[client_ip]

        while bucket and (now - bucket[0]) > self.window_seconds:
            bucket.popleft()

        if len(bucket) >= self.max_requests_per_minute:
            return Response(
                content="rate limit exceeded",
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                media_type="text/plain",
            )

        bucket.append(now)
        return await call_next(request)
