# Generated by GitHub Copilot
"""Pydantic models for llm-judge API requests and responses."""

from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


class JudgeProvider(str, Enum):
    """Supported judge providers for evaluation runs."""

    local = "local"
    openai = "openai"
    anthropic = "anthropic"
    gemini = "gemini"


class EvaluationItem(BaseModel):
    """Single evaluation item with prompt and candidate response."""

    item_id: str = Field(min_length=1, max_length=64)
    prompt: str = Field(min_length=3, max_length=5000)
    candidate_response: str = Field(min_length=2, max_length=8000)
    reference_response: Optional[str] = Field(default=None, max_length=8000)
    safety_flags: List[str] = Field(default_factory=list, max_length=16)

    @field_validator("item_id")
    @classmethod
    def validate_item_id(cls, value: str) -> str:
        """Prevent malformed identifiers that can break downstream tooling."""
        cleaned = value.strip()
        if not cleaned.replace("-", "").replace("_", "").isalnum():
            raise ValueError("item_id must be alphanumeric with optional _ or -")
        return cleaned


class RunEvaluationRequest(BaseModel):
    """Request payload for running one evaluation batch."""

    run_name: str = Field(min_length=3, max_length=96)
    judge_provider: JudgeProvider = Field(default=JudgeProvider.local)
    judge_model: str = Field(default="local-heuristic-v1", min_length=2, max_length=128)
    items: List[EvaluationItem] = Field(min_length=1, max_length=200)
    dimension_weights: Optional[Dict[str, float]] = None

    @model_validator(mode="after")
    def validate_dimension_weights(self) -> "RunEvaluationRequest":
        """Ensure dimension weights are valid and safe for score fusion."""
        if self.dimension_weights is None:
            return self

        allowed = {"factuality", "coherence", "hallucination_risk", "safety"}
        invalid = [key for key in self.dimension_weights.keys() if key not in allowed]
        if invalid:
            raise ValueError(f"unsupported dimension_weights keys: {', '.join(invalid)}")

        total = 0.0
        for value in self.dimension_weights.values():
            if value < 0.0 or value > 1.0:
                raise ValueError("dimension_weights values must be between 0 and 1")
            total += value

        if total <= 0.0:
            raise ValueError("dimension_weights total must be greater than zero")
        return self


class ItemScores(BaseModel):
    """Dimension-level scores for one evaluated item."""

    factuality: float = Field(ge=0.0, le=1.0)
    coherence: float = Field(ge=0.0, le=1.0)
    hallucination_risk: float = Field(ge=0.0, le=1.0)
    safety: float = Field(ge=0.0, le=1.0)
    final_score: float = Field(ge=0.0, le=1.0)


class ItemEvaluationResult(BaseModel):
    """Evaluation output for one item in a run."""

    item_id: str
    verdict: str
    scores: ItemScores


class RunSummary(BaseModel):
    """Aggregated metrics for a run."""

    run_name: str
    total_items: int
    average_final_score: float = Field(ge=0.0, le=1.0)
    average_factuality: float = Field(ge=0.0, le=1.0)
    average_coherence: float = Field(ge=0.0, le=1.0)
    average_hallucination_risk: float = Field(ge=0.0, le=1.0)
    average_safety: float = Field(ge=0.0, le=1.0)


class RunEvaluationResponse(BaseModel):
    """Response returned after run evaluation completes."""

    run_id: str
    requested_provider: JudgeProvider
    provider_used: JudgeProvider
    judge_model: str
    fallback_used: bool
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    summary: RunSummary
    results: List[ItemEvaluationResult]
    notes: List[str] = Field(default_factory=list)


class RunRecord(BaseModel):
    """Stored run metadata used for run listing views."""

    run_id: str
    run_name: str
    provider_used: JudgeProvider
    judge_model: str
    average_final_score: float = Field(ge=0.0, le=1.0)
    total_items: int = Field(ge=0)
    created_at: datetime


class RunsListResponse(BaseModel):
    """Response for listing recent runs."""

    runs: List[RunRecord]


class LeaderboardEntry(BaseModel):
    """Aggregated ranking entry across stored runs."""

    judge_model: str
    provider_used: JudgeProvider
    run_count: int = Field(ge=0)
    average_final_score: float = Field(ge=0.0, le=1.0)


class LeaderboardResponse(BaseModel):
    """Response for leaderboard endpoint."""

    entries: List[LeaderboardEntry]
