# Generated by GitHub Copilot
"""Judge provider resolution and fallback handling."""

from dataclasses import dataclass

from app.config import Settings
from app.models import JudgeProvider


@dataclass(frozen=True)
class ProviderResolution:
    """Provider decision outcome used by the service layer."""

    provider_used: JudgeProvider
    fallback_note: str | None


def _is_key_available(provider: JudgeProvider, settings: Settings) -> bool:
    """Check whether provider credentials are configured for selected vendor."""
    if provider == JudgeProvider.openai:
        return bool(settings.openai_api_key)
    if provider == JudgeProvider.anthropic:
        return bool(settings.anthropic_api_key)
    if provider == JudgeProvider.gemini:
        return bool(settings.gemini_api_key)
    return True


def resolve_provider(requested_provider: JudgeProvider, settings: Settings) -> ProviderResolution:
    """Resolve provider with fallback to local judge when external keys are missing."""
    if requested_provider == JudgeProvider.local:
        return ProviderResolution(provider_used=JudgeProvider.local, fallback_note=None)

    if _is_key_available(requested_provider, settings):
        if settings.strict_provider:
            raise ValueError(
                f"{requested_provider.value} adapter is not enabled in v0.1.0; use local provider"
            )
        return ProviderResolution(
            provider_used=JudgeProvider.local,
            fallback_note=(
                f"{requested_provider.value} key is configured, but adapter is pending; used local deterministic judge"
            ),
        )

    if settings.strict_provider:
        raise ValueError(
            f"{requested_provider.value} provider requested but API key is not configured"
        )

    return ProviderResolution(
        provider_used=JudgeProvider.local,
        fallback_note=(
            f"{requested_provider.value} key missing; used local deterministic judge fallback"
        ),
    )
