# Generated by GitHub Copilot
"""Service orchestration for llm-judge evaluation and leaderboard flows."""

from __future__ import annotations

from datetime import datetime
from statistics import mean
from typing import Dict
from uuid import uuid4

from app.config import Settings
from app.models import (
    ItemEvaluationResult,
    ItemScores,
    LeaderboardEntry,
    LeaderboardResponse,
    RunEvaluationRequest,
    RunEvaluationResponse,
    RunRecord,
    RunsListResponse,
    RunSummary,
)
from app.providers import resolve_provider
from app.scoring import evaluate_local_item
from app.store import SQLiteRunStore


DEFAULT_WEIGHTS: Dict[str, float] = {
    "factuality": 0.35,
    "coherence": 0.25,
    "hallucination_risk": 0.25,
    "safety": 0.15,
}


def _resolve_weights(custom_weights: Dict[str, float] | None) -> Dict[str, float]:
    """Return normalized score weights, using defaults when none are provided."""
    if custom_weights is None:
        return DEFAULT_WEIGHTS.copy()

    merged = DEFAULT_WEIGHTS.copy()
    merged.update(custom_weights)

    total = sum(merged.values())
    if total <= 0.0:
        raise ValueError("dimension weights must sum to greater than zero")

    return {key: value / total for key, value in merged.items()}


def _verdict_for_score(final_score: float) -> str:
    """Map final score to review verdict tiers for quick triage."""
    if final_score >= 0.75:
        return "pass"
    if final_score >= 0.5:
        return "review"
    return "fail"


def evaluate_run(
    payload: RunEvaluationRequest,
    settings: Settings,
    store: SQLiteRunStore,
) -> RunEvaluationResponse:
    """Evaluate a run payload, persist results, and return rich summary output."""
    weights = _resolve_weights(payload.dimension_weights)
    resolution = resolve_provider(payload.judge_provider, settings)

    item_results_raw: list[dict[str, object]] = []
    for item in payload.items:
        scores = evaluate_local_item(
            prompt=item.prompt,
            candidate_response=item.candidate_response,
            reference_response=item.reference_response,
            safety_flags=item.safety_flags,
            dimension_weights=weights,
        )

        item_results_raw.append(
            {
                "item_id": item.item_id,
                "verdict": _verdict_for_score(float(scores["final_score"])),
                "scores": scores,
            }
        )

    final_scores = [float(item["scores"]["final_score"]) for item in item_results_raw]
    factuality_scores = [float(item["scores"]["factuality"]) for item in item_results_raw]
    coherence_scores = [float(item["scores"]["coherence"]) for item in item_results_raw]
    hallucination_scores = [
        float(item["scores"]["hallucination_risk"]) for item in item_results_raw
    ]
    safety_scores = [float(item["scores"]["safety"]) for item in item_results_raw]

    run_id = uuid4().hex
    average_final_score = round(mean(final_scores), 6)

    created_at = store.save_run(
        run_id=run_id,
        run_name=payload.run_name,
        requested_provider=payload.judge_provider.value,
        provider_used=resolution.provider_used.value,
        judge_model=payload.judge_model,
        fallback_note=resolution.fallback_note,
        average_final_score=average_final_score,
        total_items=len(item_results_raw),
        item_results=item_results_raw,
    )

    summary = RunSummary(
        run_name=payload.run_name,
        total_items=len(item_results_raw),
        average_final_score=average_final_score,
        average_factuality=round(mean(factuality_scores), 6),
        average_coherence=round(mean(coherence_scores), 6),
        average_hallucination_risk=round(mean(hallucination_scores), 6),
        average_safety=round(mean(safety_scores), 6),
    )

    typed_results = [
        ItemEvaluationResult(
            item_id=str(item["item_id"]),
            verdict=str(item["verdict"]),
            scores=ItemScores(**item["scores"]),
        )
        for item in item_results_raw
    ]

    notes: list[str] = []
    if resolution.fallback_note:
        notes.append(resolution.fallback_note)

    return RunEvaluationResponse(
        run_id=run_id,
        requested_provider=payload.judge_provider,
        provider_used=resolution.provider_used,
        judge_model=payload.judge_model,
        fallback_used=resolution.fallback_note is not None,
        evaluated_at=created_at,
        summary=summary,
        results=typed_results,
        notes=notes,
    )


def list_recent_runs(store: SQLiteRunStore, limit: int = 25) -> RunsListResponse:
    """List persisted runs for dashboard history views."""
    rows = store.list_runs(limit=limit)
    records: list[RunRecord] = []

    for row in rows:
        created = datetime.fromisoformat(str(row["created_at"]))
        records.append(
            RunRecord(
                run_id=str(row["run_id"]),
                run_name=str(row["run_name"]),
                provider_used=str(row["provider_used"]),
                judge_model=str(row["judge_model"]),
                average_final_score=float(row["average_final_score"]),
                total_items=int(row["total_items"]),
                created_at=created,
            )
        )

    return RunsListResponse(runs=records)


def get_leaderboard(store: SQLiteRunStore, limit: int = 20) -> LeaderboardResponse:
    """Return model-level leaderboard aggregation from stored runs."""
    rows = store.leaderboard(limit=limit)
    entries = [
        LeaderboardEntry(
            judge_model=str(row["judge_model"]),
            provider_used=str(row["provider_used"]),
            run_count=int(row["run_count"]),
            average_final_score=float(row["average_final_score"]),
        )
        for row in rows
    ]
    return LeaderboardResponse(entries=entries)
