# Generated by GitHub Copilot
"""SQLite persistence for evaluation runs and leaderboard queries."""

from __future__ import annotations

from datetime import datetime, timezone
import os
import sqlite3
from threading import Lock
from typing import Dict, List


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS eval_runs (
    run_id TEXT PRIMARY KEY,
    run_name TEXT NOT NULL,
    requested_provider TEXT NOT NULL,
    provider_used TEXT NOT NULL,
    judge_model TEXT NOT NULL,
    fallback_note TEXT,
    average_final_score REAL NOT NULL,
    total_items INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS eval_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    factuality REAL NOT NULL,
    coherence REAL NOT NULL,
    hallucination_risk REAL NOT NULL,
    safety REAL NOT NULL,
    final_score REAL NOT NULL,
    verdict TEXT NOT NULL,
    FOREIGN KEY(run_id) REFERENCES eval_runs(run_id)
);

CREATE INDEX IF NOT EXISTS idx_eval_runs_created_at ON eval_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_eval_items_run_id ON eval_items(run_id);
"""


class SQLiteRunStore:
    """Persist and query evaluation runs with a thread-safe SQLite wrapper."""

    def __init__(self, db_path: str):
        """Initialize the store and ensure schema exists."""
        self.db_path = db_path
        self._lock = Lock()

        directory = os.path.dirname(db_path)
        if directory:
            os.makedirs(directory, exist_ok=True)

        self._initialize_schema()

    def _connect(self) -> sqlite3.Connection:
        """Create a new SQLite connection configured for row dictionaries."""
        connection = sqlite3.connect(self.db_path, timeout=15, check_same_thread=False)
        connection.row_factory = sqlite3.Row
        return connection

    def _initialize_schema(self) -> None:
        """Create baseline tables and indexes when missing."""
        with self._lock:
            with self._connect() as connection:
                connection.executescript(SCHEMA_SQL)
                connection.commit()

    def save_run(
        self,
        run_id: str,
        run_name: str,
        requested_provider: str,
        provider_used: str,
        judge_model: str,
        fallback_note: str | None,
        average_final_score: float,
        total_items: int,
        item_results: List[Dict[str, object]],
    ) -> datetime:
        """Persist run metadata and item-level scores atomically."""
        created_at = datetime.now(timezone.utc)

        with self._lock:
            with self._connect() as connection:
                connection.execute(
                    """
                    INSERT INTO eval_runs (
                        run_id, run_name, requested_provider, provider_used,
                        judge_model, fallback_note, average_final_score,
                        total_items, created_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        run_id,
                        run_name,
                        requested_provider,
                        provider_used,
                        judge_model,
                        fallback_note,
                        float(average_final_score),
                        int(total_items),
                        created_at.isoformat(),
                    ),
                )

                item_rows = []
                for item in item_results:
                    scores = item["scores"]
                    item_rows.append(
                        (
                            run_id,
                            str(item["item_id"]),
                            float(scores["factuality"]),
                            float(scores["coherence"]),
                            float(scores["hallucination_risk"]),
                            float(scores["safety"]),
                            float(scores["final_score"]),
                            str(item["verdict"]),
                        )
                    )

                connection.executemany(
                    """
                    INSERT INTO eval_items (
                        run_id, item_id, factuality, coherence,
                        hallucination_risk, safety, final_score, verdict
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    item_rows,
                )
                connection.commit()

        return created_at

    def list_runs(self, limit: int = 25) -> List[Dict[str, object]]:
        """Return recent evaluation runs ordered by creation timestamp."""
        bounded_limit = max(1, min(200, int(limit)))
        with self._lock:
            with self._connect() as connection:
                cursor = connection.execute(
                    """
                    SELECT run_id, run_name, provider_used, judge_model,
                           average_final_score, total_items, created_at
                    FROM eval_runs
                    ORDER BY datetime(created_at) DESC
                    LIMIT ?
                    """,
                    (bounded_limit,),
                )
                rows = cursor.fetchall()

        return [dict(row) for row in rows]

    def leaderboard(self, limit: int = 20) -> List[Dict[str, object]]:
        """Return aggregated ranking grouped by model and provider."""
        bounded_limit = max(1, min(200, int(limit)))
        with self._lock:
            with self._connect() as connection:
                cursor = connection.execute(
                    """
                    SELECT judge_model, provider_used,
                           COUNT(*) AS run_count,
                           AVG(average_final_score) AS average_final_score
                    FROM eval_runs
                    GROUP BY judge_model, provider_used
                    ORDER BY average_final_score DESC, run_count DESC
                    LIMIT ?
                    """,
                    (bounded_limit,),
                )
                rows = cursor.fetchall()

        return [dict(row) for row in rows]
