// Generated by GitHub Copilot
import { FormEvent, useEffect, useMemo, useState } from "react";

import { SummaryCard } from "./components/SummaryCard";
import {
  EvaluationItem,
  LeaderboardResponse,
  RunEvaluationResponse,
  RunsListResponse,
  fetchLeaderboard,
  fetchRuns,
  runEvaluation
} from "./lib/api";

const sampleItems: EvaluationItem[] = [
  {
    item_id: "faq-1",
    prompt: "How do I reset my account password?",
    candidate_response:
      "Open account settings, select security, and use the password reset option.",
    reference_response:
      "Go to account settings and choose the password reset option under security.",
    safety_flags: []
  },
  {
    item_id: "faq-2",
    prompt: "What is your refund policy?",
    candidate_response:
      "You can request refunds within 30 days through billing support.",
    reference_response:
      "Refund requests are accepted within 30 days via the billing support channel.",
    safety_flags: []
  }
];

const sampleWeights = {
  factuality: 0.35,
  coherence: 0.25,
  hallucination_risk: 0.25,
  safety: 0.15
};

/**
 * Generated by GitHub Copilot
 * Main UI for creating evaluation runs and reviewing leaderboard output.
 */
export default function App(): JSX.Element {
  const [runName, setRunName] = useState("support-bot-v2-eval");
  const [judgeProvider, setJudgeProvider] = useState("local");
  const [judgeModel, setJudgeModel] = useState("local-heuristic-v1");
  const [itemsJson, setItemsJson] = useState(JSON.stringify(sampleItems, null, 2));
  const [weightsJson, setWeightsJson] = useState(JSON.stringify(sampleWeights, null, 2));

  const [runResult, setRunResult] = useState<RunEvaluationResponse | null>(null);
  const [leaderboard, setLeaderboard] = useState<LeaderboardResponse | null>(null);
  const [recentRuns, setRecentRuns] = useState<RunsListResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const statusLabel = useMemo(() => {
    if (!runResult) {
      return "No run yet";
    }
    if (runResult.summary.average_final_score >= 0.75) {
      return "Strong";
    }
    if (runResult.summary.average_final_score >= 0.5) {
      return "Needs review";
    }
    return "High risk";
  }, [runResult]);

  /**
   * Generated by GitHub Copilot
   * Refresh leaderboard and recent run history panels.
   */
  async function refreshInsights(): Promise<void> {
    setIsRefreshing(true);
    try {
      const [leaderboardResponse, runsResponse] = await Promise.all([
        fetchLeaderboard(10),
        fetchRuns(10)
      ]);
      setLeaderboard(leaderboardResponse);
      setRecentRuns(runsResponse);
    } catch (refreshError) {
      const message =
        refreshError instanceof Error
          ? refreshError.message
          : "unable to refresh leaderboard";
      setError(message);
    } finally {
      setIsRefreshing(false);
    }
  }

  useEffect(() => {
    void refreshInsights();
  }, []);

  /**
   * Generated by GitHub Copilot
   * Parse form JSON payload and execute evaluation run.
   */
  async function handleSubmit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    setError(null);

    try {
      const parsedItems = JSON.parse(itemsJson) as EvaluationItem[];
      const parsedWeights = JSON.parse(weightsJson) as Record<string, number>;

      setIsLoading(true);
      const response = await runEvaluation({
        run_name: runName.trim(),
        judge_provider: judgeProvider as "local" | "openai" | "anthropic" | "gemini",
        judge_model: judgeModel.trim(),
        items: parsedItems,
        dimension_weights: parsedWeights
      });
      setRunResult(response);
      await refreshInsights();
    } catch (submitError) {
      const message =
        submitError instanceof Error
          ? submitError.message
          : "unable to run evaluation";
      setError(message);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="app-shell">
      <header className="hero" aria-labelledby="page-title">
        <p className="eyebrow">LLM Evaluation Ops</p>
        <h1 id="page-title">llm-judge control panel</h1>
        <p>
          Run deterministic evaluation batches, compare scoring performance, and monitor
          leaderboard shifts before shipping model changes.
        </p>
      </header>

      <main>
        <section className="panel" aria-labelledby="run-heading">
          <h2 id="run-heading">Run Evaluation</h2>
          <form className="judge-form" onSubmit={handleSubmit}>
            <label htmlFor="runName">Run Name</label>
            <input
              id="runName"
              value={runName}
              onChange={(event) => setRunName(event.target.value)}
              required
            />

            <label htmlFor="judgeProvider">Judge Provider</label>
            <select
              id="judgeProvider"
              value={judgeProvider}
              onChange={(event) => setJudgeProvider(event.target.value)}
            >
              <option value="local">local</option>
              <option value="openai">openai</option>
              <option value="anthropic">anthropic</option>
              <option value="gemini">gemini</option>
            </select>

            <label htmlFor="judgeModel">Judge Model</label>
            <input
              id="judgeModel"
              value={judgeModel}
              onChange={(event) => setJudgeModel(event.target.value)}
              required
            />

            <label htmlFor="itemsJson">Evaluation Items (JSON)</label>
            <textarea
              id="itemsJson"
              value={itemsJson}
              onChange={(event) => setItemsJson(event.target.value)}
              rows={12}
              required
            />

            <label htmlFor="weightsJson">Dimension Weights (JSON)</label>
            <textarea
              id="weightsJson"
              value={weightsJson}
              onChange={(event) => setWeightsJson(event.target.value)}
              rows={7}
              required
            />

            <button type="submit" disabled={isLoading}>
              {isLoading ? "Evaluating..." : "Run Evaluation"}
            </button>
          </form>

          {error ? (
            <p className="error-banner" role="alert" aria-live="polite">
              {error}
            </p>
          ) : null}
        </section>

        <section className="panel" aria-labelledby="summary-heading">
          <div className="panel-row">
            <h2 id="summary-heading">Run Summary</h2>
            <button
              type="button"
              onClick={() => void refreshInsights()}
              disabled={isRefreshing}
            >
              {isRefreshing ? "Refreshing..." : "Refresh Insights"}
            </button>
          </div>

          <div className="summary-grid">
            <SummaryCard
              title="Status"
              value={statusLabel}
              tone={
                statusLabel === "Strong"
                  ? "ok"
                  : statusLabel === "Needs review"
                    ? "neutral"
                    : "alert"
              }
            />
            <SummaryCard
              title="Avg Final Score"
              value={
                runResult ? runResult.summary.average_final_score.toFixed(3) : "0.000"
              }
              tone="neutral"
            />
            <SummaryCard
              title="Items"
              value={runResult ? String(runResult.summary.total_items) : "0"}
              tone="neutral"
            />
          </div>

          {runResult ? (
            <>
              <h3>Item Results</h3>
              <div className="table-wrap" role="region" aria-label="Item result table">
                <table>
                  <thead>
                    <tr>
                      <th scope="col">Item</th>
                      <th scope="col">Verdict</th>
                      <th scope="col">Final</th>
                      <th scope="col">Factuality</th>
                      <th scope="col">Coherence</th>
                      <th scope="col">Hallucination Risk</th>
                      <th scope="col">Safety</th>
                    </tr>
                  </thead>
                  <tbody>
                    {runResult.results.map((result) => (
                      <tr key={result.item_id}>
                        <td>{result.item_id}</td>
                        <td>
                          <strong
                            className={
                              result.verdict === "pass"
                                ? "status-ok"
                                : result.verdict === "review"
                                  ? "status-neutral"
                                  : "status-alert"
                            }
                          >
                            {result.verdict}
                          </strong>
                        </td>
                        <td>{result.scores.final_score.toFixed(3)}</td>
                        <td>{result.scores.factuality.toFixed(3)}</td>
                        <td>{result.scores.coherence.toFixed(3)}</td>
                        <td>{result.scores.hallucination_risk.toFixed(3)}</td>
                        <td>{result.scores.safety.toFixed(3)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {runResult.notes.length > 0 ? (
                <div className="notes">
                  <h3>Run Notes</h3>
                  <ul>
                    {runResult.notes.map((note) => (
                      <li key={note}>{note}</li>
                    ))}
                  </ul>
                </div>
              ) : null}
            </>
          ) : (
            <p className="placeholder">Run an evaluation to view detailed scoring output.</p>
          )}
        </section>

        <section className="panel" aria-labelledby="leaderboard-heading">
          <h2 id="leaderboard-heading">Leaderboard</h2>
          <div className="table-wrap" role="region" aria-label="Leaderboard table">
            <table>
              <thead>
                <tr>
                  <th scope="col">Model</th>
                  <th scope="col">Provider</th>
                  <th scope="col">Runs</th>
                  <th scope="col">Avg Final Score</th>
                </tr>
              </thead>
              <tbody>
                {leaderboard?.entries.length ? (
                  leaderboard.entries.map((entry) => (
                    <tr key={`${entry.judge_model}-${entry.provider_used}`}>
                      <td>{entry.judge_model}</td>
                      <td>{entry.provider_used}</td>
                      <td>{entry.run_count}</td>
                      <td>{entry.average_final_score.toFixed(3)}</td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={4}>No leaderboard entries yet.</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </section>

        <section className="panel" aria-labelledby="runs-heading">
          <h2 id="runs-heading">Recent Runs</h2>
          <div className="table-wrap" role="region" aria-label="Recent runs table">
            <table>
              <thead>
                <tr>
                  <th scope="col">Run</th>
                  <th scope="col">Model</th>
                  <th scope="col">Provider</th>
                  <th scope="col">Items</th>
                  <th scope="col">Avg Score</th>
                </tr>
              </thead>
              <tbody>
                {recentRuns?.runs.length ? (
                  recentRuns.runs.map((run) => (
                    <tr key={run.run_id}>
                      <td>{run.run_name}</td>
                      <td>{run.judge_model}</td>
                      <td>{run.provider_used}</td>
                      <td>{run.total_items}</td>
                      <td>{run.average_final_score.toFixed(3)}</td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={5}>No runs found.</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </div>
  );
}
