# Generated by GitHub Copilot
# Bootstrap local llm-judge runtime with default environment values.

if (!(Test-Path .env)) {
    Copy-Item .env.example .env
}

docker compose --env-file .env up --build
