// Generated by GitHub Copilot
export type JudgeProvider = "local" | "openai" | "anthropic" | "gemini";

export interface EvaluationItem {
  item_id: string;
  prompt: string;
  candidate_response: string;
  reference_response?: string;
  safety_flags?: string[];
}

export interface RunEvaluationRequest {
  run_name: string;
  judge_provider: JudgeProvider;
  judge_model: string;
  items: EvaluationItem[];
  dimension_weights?: Record<string, number>;
}

export interface RunEvaluationResponse {
  run_id: string;
  requested_provider: JudgeProvider;
  provider_used: JudgeProvider;
  judge_model: string;
  fallback_used: boolean;
  evaluated_at: string;
  summary: {
    run_name: string;
    total_items: number;
    average_final_score: number;
    average_factuality: number;
    average_coherence: number;
    average_hallucination_risk: number;
    average_safety: number;
  };
  results: Array<{
    item_id: string;
    verdict: string;
    scores: {
      factuality: number;
      coherence: number;
      hallucination_risk: number;
      safety: number;
      final_score: number;
    };
  }>;
  notes: string[];
}

export interface RunsListResponse {
  runs: Array<{
    run_id: string;
    run_name: string;
    provider_used: JudgeProvider;
    judge_model: string;
    average_final_score: number;
    total_items: number;
    created_at: string;
  }>;
}

export interface LeaderboardResponse {
  entries: Array<{
    judge_model: string;
    provider_used: JudgeProvider;
    run_count: number;
    average_final_score: number;
  }>;
}

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8010";

/**
 * Generated by GitHub Copilot
 * Parse failed API responses and return a useful error message.
 */
async function buildErrorMessage(response: Response): Promise<string> {
  const fallback = `request failed with status ${response.status}`;
  try {
    const body = (await response.json()) as { detail?: string };
    return body.detail || fallback;
  } catch {
    return fallback;
  }
}

/**
 * Generated by GitHub Copilot
 * Run one evaluation batch and return item-level scoring output.
 */
export async function runEvaluation(
  payload: RunEvaluationRequest
): Promise<RunEvaluationResponse> {
  const response = await fetch(`${API_BASE_URL}/api/v1/evals/run`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    throw new Error(await buildErrorMessage(response));
  }

  return (await response.json()) as RunEvaluationResponse;
}

/**
 * Generated by GitHub Copilot
 * Fetch leaderboard aggregates for model-level ranking display.
 */
export async function fetchLeaderboard(limit = 10): Promise<LeaderboardResponse> {
  const response = await fetch(`${API_BASE_URL}/api/v1/evals/leaderboard?limit=${limit}`);
  if (!response.ok) {
    throw new Error(await buildErrorMessage(response));
  }
  return (await response.json()) as LeaderboardResponse;
}

/**
 * Generated by GitHub Copilot
 * Fetch recent runs for quick operational inspection.
 */
export async function fetchRuns(limit = 10): Promise<RunsListResponse> {
  const response = await fetch(`${API_BASE_URL}/api/v1/evals/runs?limit=${limit}`);
  if (!response.ok) {
    throw new Error(await buildErrorMessage(response));
  }
  return (await response.json()) as RunsListResponse;
}
